server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/tumblbug
#    url: jdbc:h2:~/tumblbug
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: h2
logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace